version: '3.7'

services:

  minio:
    image: ${MINIO_IMAGE}
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-net
    volumes:
      - ${MINIO_DATA_DIR}:${MINIO_DATA_DIR}
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server --console-address ":9001" ${MINIO_DATA_DIR}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  nginx:
    user: root
    image: ${NGINX_IMAGE}
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx
    ports:
      - 80:80
      - 443:443
      - 9443:9443
    networks:
      - minio-net
    depends_on:
      - minio


networks:
  minio-net:
    ipam:
      config:
        - subnet: 172.27.0.0/16
